### PR TITLE
compute mode for continuous variables with different method

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2295

@JohnnyDoorn do you have time to test this/ can you install modules again?

### CODE REVIEW

**Comment by JohnnyDoorn** [comment]
Awesome! My only concern is the footnote - it says more than 1 mode exists for the continuous variable, but is that then really the case? Is it perhaps better to simply state that for continuous variables, the highest density estimate is used? 

Also, I see that for contbinom, there is some weird rounding thing going on, or is that the case everywhere in JASP?

image

**Comment by vandenman** [comment]
> "a rudimentary analysis indicated that multiple modes may exist" -- which analysis is that?

> The "rudimentary analysis" btw is just checking if the derivative of the pdf crosses zero more than once (the derivative is zero at each mode).

I'm more than happy to leave this out though. In that case, the footnote reads:

> For continuous data, the highest density estimate is reported, but multiple modes may exist. We recommend visualizing the data to check for multimodality.

In addition, I'll mention in the help file that this footnote is shown as soon as there is any indication of multimodality.

@JohnnyDoorn, @EJWagenmakers any further suggestions?

**Comment by EJWagenmakers** [comment]
I'm happy with this

**Comment by vandenman** [comment]
@JohnnyDoorn any further feedback? The unit test failure I'll address in a separate PR (it's unrelated to the changes here).

**Comment by JohnnyDoorn** [comment]
@vandenman yeah i like how the text looks now =)

**Pull request merged**
