### PR TITLE
Raincloud: only include legend when there is second factor

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
Since the primary factor is on the x-axis, it does not need a legend - do you agree @vincentott?

### CODE REVIEW

**Comment by vincentott** [comment]
I had also thought about it but then decided to leave it as is.
Because it gives users more flexibility:

If they want to opt for the ticks only, then they can crop off the legend.
If they want to opt for the legend only (because they still want color with primaryFactor only and it might look nicer),
then they can remove the tick text in JASP or in after-editing.

**Comment by EJWagenmakers** [comment]
Maybe have the legend off by default, and allow users to add it if they wish? Can they crop the legend within JASP? Because right now, it is really redundant to the extent that it appears as a bug.
EJ

**Comment by vincentott** [comment]
>  Can they crop the legend within JASP?

Nope.

> Maybe have the legend off by default, and allow users to add it if they wish?

Yeah, that seems like a good idea.
So, then we would have an additional checkbox in the section "Axes, Caption, and Plot Size".
I guess, then the name could be "Axes, Legend, Caption, and Plot Size" instead.

And this CheckBox "Show legend" is only enabled/available/clickable if there is a primaryFactor and colorAnyway?

Is that a good implementation, @JohnnyDoorn ?

**Comment by JohnnyDoorn** [comment]
Ah, just added the option - added it below "apply color palette" because it functions a bit in a similar way.
When a second factor is added, the checkbox is greyed out. When no second factor is added, it's off by default/
I also changed "show point" to "show points" because I think that was a typo (usually we have multiple points in the raincloud). 
Screenshot 2024-06-19 at 11 02 42

**Comment by vincentott** [comment]
very cool, thanks! I think you can merge it now!

**Pull request merged**
