### PR TITLE
Outward Axis Ticks & Bigger Font Size

### PR DESCRIPTION
**Pull request by vincentott**

### CODE REVIEW

**Comment by vincentott** [comment]
As far as I can tell, the unit tests should work (because I also changed the corresponding .svg files with my commit).
Could you, e.g., @JohnnyDoorn , be so kind and check whats up here?

**Comment by JohnnyDoorn** [comment]
Could you make the font size a bit smaller? I like the size increase but this is maybe a bit too much, and more quickly will lead to axis labels overlap, and is a bit too "in your face" imo. If you compare it to descriptives plots in t-test:
image

**Comment by vincentott** [comment]
with the latest font size, you can comfortably use them in word and overleaf drafts for publications
[word_paper.pdf](https://github.com/user-attachments/files/15872716/word_paper.pdf)
[overleaf_paper.pdf](https://github.com/user-attachments/files/15872719/overleaf_paper.pdf)

**Comment by vincentott** [comment]
@JohnnyDoorn could you once again do your "update testplots" magic?
I think then, this should be ready to go into the next nightly, right?

**Comment by JohnnyDoorn** [comment]
Ah yes that looks great! Also updated the plots - for the future, you can do this by running the unit tests (`testAll()`), and then `jaspTools::manageTestPlots()`
This will show how the new plots differ from the old ones (sometimes they look identical but then there's some tiny ggplot thing that changed)

**Pull request merged**
