### PR TITLE
restructure descriptives input panel

### PR DESCRIPTION
**Pull request by Kucharssim**
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1738
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1737

### CODE REVIEW

**Comment by vandenman** [comment]
I like the changes, but I'm not sure about the places where there are 3 columns. This doesn't really adapt well to different languages, so perhaps we should stick to 2 columns max?
I also remember getting chewed out by Tim once for using 3 columns (not JASPy enough:sweat_smile:).

| English  | Spanish |
|:---:|:---:|
| image | image |

I also think that there is sometimes too much empty space. I get why there is empty space (and also that it's automatic), but I don't think it would look bad if for example `Sample size`, `Quantiles`, and `Distribution` would start right underneath each other, instead of lining out with the element in the right column. @boutinb any ideas there?

**Comment by EJWagenmakers** [comment]
quantiles and distribution could be on the same line, so that dispersion then gets its own.

**Comment by Kucharssim** [comment]
> This doesn't really adapt well to different languages, so perhaps we should stick to 2 columns max?
> I also remember getting chewed out by Tim once for using 3 columns (not JASPy enough😅).

Good catch! I will do what @EJWagenmakers suggested here.

I wonder with the "Graph right of scatter plot": I don't see anything particularly wrong with that formatting: it's two columns, and there is plenty of space on the right (in English). It seems to be a case of Spanish being simply more verbose than English, and I don't know whether it's possible to always make sure that any language will not go out of bonds just by formatting the QML forms. Perhaps a better solution would be to make sure text labels line-wrap so that the text cannot go outside of the width of the form? @boutinb

**Comment by Kucharssim** [comment]
> I also think that there is sometimes too much empty space. I get why there is empty space (and also that it's automatic), but I don't think it would look bad if for example Sample size, Quantiles, and Distribution would start right underneath each other, instead of lining out with the element in the right column. @boutinb any ideas there?

I could easily put those groups in another group which gets rid of this automatic alignment across rows. I am not sure whether this improves the situation; it looks to me quite cluttered/crammed:
Screenshot 2022-02-21 at 12 32 57

**Comment by boutinb** [comment]
@Kucharssim I could help you here if you like.

**Comment by Kucharssim** [comment]
Screenshot 2022-05-03 at 12 45 02

@vandenman is this better?

**Review by vandenman — APPROVED** [review]

**Pull request merged**
