### PR TITLE
Restore the "natural" order 

### PR DESCRIPTION
**Pull request by tomtomme**
I am still new to github, so I hope to create this pull request is the right thing to do. 
What confuses me is that my changes from February seem to be automatically included. I thought they were already pulled?!?

The really new changes I made are:
a) Changed section and variable name percentileValues to postions (as this better reflects the content of the section. Is this ok, or do other modules depend on the exact variable name?
b) Every textbook I know begins with mode median mean in this order. JASP reflects this now also in the output table.
c) Sum is a better fit for section distribution

If this commit is accepted I will reorder further items in this module to make it more beginner friendly.

### CODE REVIEW

**Comment by tomtomme** [comment]
The above conflicts confuse me even more. I clicked on "Fetch origin" in GitHub Desktop before I began my changes. But according to the above conflict message my local files did not seem up to date. What went wrong?

**Comment by vandenman** [comment]
hi @tomtomme it looks like you have some issues with GitHub, as in, there are merge conflicts between your master branch and the jaspDescriptives@master.

From 
image
I take it that you only want to push the commit from May 15th?

The reason for this is that we *squash* all the commits in a pull request into one commit to keep the history clean. So while you see multiple commits in your commit history above, the history of jasp-desktop only shows one commit:

image

To fix this, open a terminal, navigate to your directory and do
```
# create a copy of your current work on a new branch
git checkout -b backup
# set current branch to master
git checkout master
# pull the changes from jasp-desktop/jaspDescriptives, if this gives an error, you probably need to do
# git remote add upstream https://github.com/jasp-stats/jaspDescriptives.git && git fetch upstream
git fetch upstream
# reset your local master branch to jasp-desktop
git reset --hard upstream/master
# create a new branch for this pr
git checkout -b natural_order
# get only the changes for this particular commit (the one from May 15th)
git cherry-pick 11b60872a966ce140d9a894c0bedc95f4b0f2448
# push the new branch to your cloud (tomtomme/jaspDescriptives)
git push --set-upstream origin natural_order
```
and then you can use the GitHub website to make a PR from your newly created branch.

In the future, you can avoid this by using a separate branch for each feature you work on. Then you can keep your master branch up to date with jaspDesktop@master and whenever you'd make a new branch you can use that master branch as starting point. That way you'd have the squashed commits in your history instead of the individual commits. This is also what I did in the steps above.

**Comment by tomtomme** [comment]
I tried this. Below are again merge conflicts. I have no idea where they come from or how to read them.
There are things like this: 

<<<<<<< HEAD
Date: 2019-08-29
=======
Date: 2021-05-15
>>>>>>> 11b6087 (Restore the "natural" order)

I only changed the date. Why is the old date back again? What does this HEAD thing mean and why was the last row added?

[tom@tomspc jaspDescriptives]$ git checkout -b backup
Zu neuem Branch 'backup' gewechselt
[tom@tomspc jaspDescriptives]$ git checkout master
Zu Branch 'master' gewechselt
Ihr Branch ist auf demselben Stand wie 'origin/master'.
[tom@tomspc jaspDescriptives]$ git fetch upstream
[tom@tomspc jaspDescriptives]$ git reset --hard upstream/master
HEAD ist jetzt bei 95f3fc6 increase top margin for discrete distribution plots & add a unit test (#41)
[tom@tomspc jaspDescriptives]$ git checkout -b natural_order
Zu neuem Branch 'natural_order' gewechselt
[tom@tomspc jaspDescriptives]$ git cherry-pick 11b60872a966ce140d9a894c0bedc95f4b0f2448
automatischer Merge von inst/qml/Descriptives.qml
automatischer Merge von inst/Description.qml
KONFLIKT (Inhalt): Merge-Konflikt in inst/Description.qml
automatischer Merge von R/descriptives.R
KONFLIKT (Inhalt): Merge-Konflikt in R/descriptives.R
automatischer Merge von DESCRIPTION
KONFLIKT (Inhalt): Merge-Konflikt in DESCRIPTION
error: Konnte 11b6087... (Restore the "natural" order) nicht anwenden
Hinweis: nach Auflösung der Konflikte markieren Sie die korrigierten Pfade
Hinweis: mit 'git add <Pfade>' oder 'git rm <Pfade>' und tragen Sie das Ergebnis mit
Hinweis: 'git commit' ein
[tom@tomspc jaspDescriptives]$ git push --set-upstream origin natural_order

**Comment by tomtomme** [comment]
I solved the conflicts manually to my best knowledge and just deleted the doubled old lines of code that I intended to change. I then commited this to master. Was this correct? I feel like a total noob.... Is there an easy / beginner github manual you could recommend?

**Comment by tomtomme** [comment]
I gave this a completely new try here: 
https://github.com/jasp-stats/jaspDescriptives/pull/43

**Pull request closed without merging**
